############################################################################
# BK7258 internal-DAC audio bring-up test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = audio_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_AUDIO_TEST)

MAINSRC = audio_test_main.c

include $(APPDIR)/Application.mk
