############################################################################
# BK7258 peripheral self-test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = periph_selftest
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_PERIPH_SELFTEST)

MAINSRC = periph_selftest_main.c

include $(APPDIR)/Application.mk
