############################################################################
# Network benchmark with mailbox instrumentation - Makefile
############################################################################
include $(APPDIR)/Make.defs
PROGNAME  = netbench
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_NETBENCH)
MAINSRC = netbench_main.c
include $(APPDIR)/Application.mk
