############################################################################
# BK7258 V4L2 M2M JPEG encoder test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = jpeg_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_JPEG_TEST)

MAINSRC = jpeg_test_main.c

include $(APPDIR)/Application.mk
