############################################################################
# VelaSight social-cue state machine - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = social_cue
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_SOCIAL_CUE)

MAINSRC = social_cue_main.c

include $(APPDIR)/Application.mk
