/****************************************************************************
 * BK7258 Mailbox V2 and mailbox-UART wire ABI.
 ****************************************************************************/

#ifndef __VENDOR_BEKEN_CHIPS_BK7258_HARDWARE_BK7258_MBOX_H
#define __VENDOR_BEKEN_CHIPS_BK7258_HARDWARE_BK7258_MBOX_H

#include <nuttx/config.h>

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>

#define BK7258_MBOX_FIFO_SIZE       8u
#define BK7258_MBOX_IRQ             79
#define BK7258_MBOX_CMD_FIFO        1u
#define BK7258_MBOX_ACK_FIFO        0u
#define BK7258_MBOX_RAW_KICK        0x534d5001u

#define BK7258_MBOX_REG(n)          (BK7258_MBOX0_BASE + ((n) * 4u))
#define BK7258_MBOX_CTRL            BK7258_MBOX_REG(0x02)
#define BK7258_MBOX_CH0_STATUS      BK7258_MBOX_REG(0x18)
#define BK7258_MBOX_CH1_CFG         BK7258_MBOX_REG(0x20)
#define BK7258_MBOX_CH1_FIFO_CFG    BK7258_MBOX_REG(0x21)
#define BK7258_MBOX_CH1_TDATA0      BK7258_MBOX_REG(0x22)
#define BK7258_MBOX_CH1_TDATA1      BK7258_MBOX_REG(0x23)
#define BK7258_MBOX_CH1_TID         BK7258_MBOX_REG(0x24)
#define BK7258_MBOX_CH1_SID         BK7258_MBOX_REG(0x25)
#define BK7258_MBOX_CH1_RDATA0      BK7258_MBOX_REG(0x26)
#define BK7258_MBOX_CH1_RDATA1      BK7258_MBOX_REG(0x27)
#define BK7258_MBOX_CH1_STATUS      BK7258_MBOX_REG(0x28)
#define BK7258_MBOX_CH2_CFG         BK7258_MBOX_REG(0x30)
#define BK7258_MBOX_CH2_FIFO_CFG    BK7258_MBOX_REG(0x31)
#define BK7258_MBOX_CH2_TDATA0      BK7258_MBOX_REG(0x32)
#define BK7258_MBOX_CH2_TDATA1      BK7258_MBOX_REG(0x33)
#define BK7258_MBOX_CH2_TID         BK7258_MBOX_REG(0x34)
#define BK7258_MBOX_CH2_SID         BK7258_MBOX_REG(0x35)
#define BK7258_MBOX_CH2_RDATA0      BK7258_MBOX_REG(0x36)
#define BK7258_MBOX_CH2_RDATA1      BK7258_MBOX_REG(0x37)
#define BK7258_MBOX_CH2_STATUS      BK7258_MBOX_REG(0x38)

#define BK7258_MBOX_CFG_INT_EN         (1u << 8)
#define BK7258_MBOX_CFG_WRERR_EN       (1u << 9)
#define BK7258_MBOX_CFG_RDERR_EN       (1u << 10)
#define BK7258_MBOX_CFG_WRFULL_EN      (1u << 11)
#define BK7258_MBOX_CFG_WRERR_STATUS   (1u << 16)
#define BK7258_MBOX_CFG_RDERR_STATUS   (1u << 17)
#define BK7258_MBOX_CFG_WRFULL_STATUS  (1u << 18)
#define BK7258_MBOX_CFG_ERROR_STATUS   \
  (BK7258_MBOX_CFG_WRERR_STATUS | BK7258_MBOX_CFG_RDERR_STATUS | \
   BK7258_MBOX_CFG_WRFULL_STATUS)
#define BK7258_MBOX_CFG_RW_MASK        0x00000fffu

#define BK7258_MB_MESSAGE_SIZE      16u
#define BK7258_MB_HEADER_CMD_SHIFT  0u
#define BK7258_MB_HEADER_CMD_MASK   (0xffu << BK7258_MB_HEADER_CMD_SHIFT)
#define BK7258_MB_HEADER_STATE_SHIFT 8u
#define BK7258_MB_HEADER_STATE_MASK (0x0fu << BK7258_MB_HEADER_STATE_SHIFT)
#define BK7258_MB_HEADER_CTRL_SHIFT 12u
#define BK7258_MB_HEADER_CTRL_MASK  (0x0fu << BK7258_MB_HEADER_CTRL_SHIFT)
#define BK7258_MB_HEADER_SEQ_SHIFT  16u
#define BK7258_MB_HEADER_SEQ_MASK   (0xffu << BK7258_MB_HEADER_SEQ_SHIFT)
#define BK7258_MB_HEADER_CHAN_SHIFT 24u
#define BK7258_MB_HEADER_CHAN_MASK  (0xffu << BK7258_MB_HEADER_CHAN_SHIFT)

_Static_assert((BK7258_MB_HEADER_CMD_MASK |
                BK7258_MB_HEADER_STATE_MASK |
                BK7258_MB_HEADER_CTRL_MASK |
                BK7258_MB_HEADER_SEQ_MASK |
                BK7258_MB_HEADER_CHAN_MASK) == UINT32_MAX,
               "mailbox header masks must cover exactly 32 bits");
_Static_assert((BK7258_MB_HEADER_STATE_MASK &
                BK7258_MB_HEADER_CTRL_MASK) == 0 &&
               (BK7258_MB_HEADER_SEQ_MASK &
                BK7258_MB_HEADER_CHAN_MASK) == 0,
               "mailbox header masks overlap");

#define BK7258_MB_CTRL_ACK_BOX      0x01u
#define BK7258_MB_CTRL_SYNC_TX      0x02u
#define BK7258_MB_CTRL_RESET        0x04u
#define BK7258_MB_STATE_COM_FAIL    0x01u

#define BK7258_MB_CHAN_HW_CTRL_TX   0x10u
#define BK7258_MB_CHAN_PWC_TX       0x12u
#define BK7258_MB_CHAN_WIFI_CMD_TX  0x14u
#define BK7258_MB_CHAN_WIFI_DATA_TX 0x15u
#define BK7258_MB_CHAN_UART0_TX     0x19u
#define BK7258_MB_CHAN_PWC_RX       0x42u
#define BK7258_MB_CHAN_WIFI_CMD_RX  0x44u
#define BK7258_MB_CHAN_WIFI_DATA_RX 0x45u
#define BK7258_MB_CHAN_UART0_RX     0x49u
#define BK7258_MB_CHAN_SARADC_RX    0x4cu

#define BK7258_MB_UART_DATA         0u
#define BK7258_MB_UART_STATE        1u
#define BK7258_MB_UART_CHUNK_SIZE   128u

/* These values are generated by the app_ab RAM layout.  The linker script
 * independently asserts the complete SWAP reservation.
 */

#define BK7258_CP_RAM_START         0x28064000u
#define BK7258_CP_RAM_END           0x2809f700u
#define BK7258_SWAP_BASE            0x2809f800u
#define BK7258_SWAP_SIZE            0x00000800u
#define BK7258_IPC_TX_ADDRESS       0x2809f900u
#define BK7258_IPC_TX_SIZE          0x00000080u
#define BK7258_MB_UART_RX_ADDRESS   0x2809fc00u
#define BK7258_MB_UART_TX_ADDRESS   0x2809fd00u
#define BK7258_MB_SHARED_TX_START   BK7258_IPC_TX_ADDRESS
#define BK7258_MB_SHARED_TX_SIZE    \
  (BK7258_MB_UART_TX_ADDRESS + BK7258_MB_UART_CHUNK_SIZE - \
   BK7258_MB_SHARED_TX_START)

_Static_assert(BK7258_IPC_TX_ADDRESS >= BK7258_SWAP_BASE &&
               BK7258_IPC_TX_ADDRESS + BK7258_IPC_TX_SIZE <=
               BK7258_SWAP_BASE + BK7258_SWAP_SIZE,
               "IPC TX buffer lies outside SWAP");
_Static_assert((BK7258_IPC_TX_ADDRESS & 31u) == 0,
               "IPC TX buffer must be cache-line aligned");
_Static_assert(BK7258_MB_SHARED_TX_START + BK7258_MB_SHARED_TX_SIZE <=
               BK7258_SWAP_BASE + BK7258_SWAP_SIZE,
               "mailbox shared TX window lies outside SWAP");
_Static_assert(BK7258_MB_UART_RX_ADDRESS >= BK7258_SWAP_BASE &&
               BK7258_MB_UART_RX_ADDRESS + BK7258_MB_UART_CHUNK_SIZE <=
               BK7258_SWAP_BASE + BK7258_SWAP_SIZE,
               "mailbox UART RX lies outside SWAP");
_Static_assert(BK7258_MB_UART_TX_ADDRESS >= BK7258_SWAP_BASE &&
               BK7258_MB_UART_TX_ADDRESS + BK7258_MB_UART_CHUNK_SIZE <=
               BK7258_SWAP_BASE + BK7258_SWAP_SIZE,
               "mailbox UART TX lies outside SWAP");
_Static_assert((BK7258_MB_UART_RX_ADDRESS & 31u) == 0 &&
               (BK7258_MB_UART_TX_ADDRESS & 31u) == 0,
               "mailbox UART buffers must be cache-line aligned");

struct bk7258_mb_wire_message
{
  uint32_t header;
  uint32_t payload_address;
  uint16_t payload_length;
  uint8_t flags;
  uint8_t crc8;
  uint32_t reserved;
};

_Static_assert(sizeof(struct bk7258_mb_wire_message) ==
               BK7258_MB_MESSAGE_SIZE, "mailbox message ABI size");
_Static_assert(offsetof(struct bk7258_mb_wire_message, header) == 0,
               "mailbox header ABI offset");
_Static_assert(offsetof(struct bk7258_mb_wire_message, payload_address) == 4,
               "mailbox payload ABI offset");
_Static_assert(offsetof(struct bk7258_mb_wire_message, payload_length) == 8,
               "mailbox length ABI offset");
_Static_assert(offsetof(struct bk7258_mb_wire_message, flags) == 10,
               "mailbox flags ABI offset");
_Static_assert(offsetof(struct bk7258_mb_wire_message, crc8) == 11,
               "mailbox CRC ABI offset");
_Static_assert(offsetof(struct bk7258_mb_wire_message, reserved) == 12,
               "mailbox reserved ABI offset");

static inline uint8_t
bk7258_mb_header_cmd(const struct bk7258_mb_wire_message *message)
{
  return (message->header & BK7258_MB_HEADER_CMD_MASK) >>
         BK7258_MB_HEADER_CMD_SHIFT;
}

static inline uint8_t
bk7258_mb_header_state(const struct bk7258_mb_wire_message *message)
{
  return (message->header & BK7258_MB_HEADER_STATE_MASK) >>
         BK7258_MB_HEADER_STATE_SHIFT;
}

static inline uint8_t
bk7258_mb_header_ctrl(const struct bk7258_mb_wire_message *message)
{
  return (message->header & BK7258_MB_HEADER_CTRL_MASK) >>
         BK7258_MB_HEADER_CTRL_SHIFT;
}

static inline uint8_t
bk7258_mb_header_seq(const struct bk7258_mb_wire_message *message)
{
  return (message->header & BK7258_MB_HEADER_SEQ_MASK) >>
         BK7258_MB_HEADER_SEQ_SHIFT;
}

static inline uint8_t
bk7258_mb_header_channel(const struct bk7258_mb_wire_message *message)
{
  return (message->header & BK7258_MB_HEADER_CHAN_MASK) >>
         BK7258_MB_HEADER_CHAN_SHIFT;
}

static inline uint32_t bk7258_mb_make_header(uint8_t command, uint8_t state,
                                             uint8_t control, uint8_t sequence,
                                             uint8_t channel)
{
  return ((uint32_t)command << BK7258_MB_HEADER_CMD_SHIFT) |
         ((uint32_t)(state & 0x0fu) << BK7258_MB_HEADER_STATE_SHIFT) |
         ((uint32_t)(control & 0x0fu) << BK7258_MB_HEADER_CTRL_SHIFT) |
         ((uint32_t)sequence << BK7258_MB_HEADER_SEQ_SHIFT) |
         ((uint32_t)channel << BK7258_MB_HEADER_CHAN_SHIFT);
}

typedef struct
{
  uint8_t src_cpu;
  uint8_t dest_cpu;
  uint32_t data[2];
} bk7258_mbox_message_t;

struct bk7258_mbox_stats
{
  uint32_t rx_messages;
  uint32_t bad_source;
  uint32_t bad_length;
  uint32_t bad_address;
  uint32_t write_error;
  uint32_t read_error;
  uint32_t write_full;
  uint32_t descriptor_full;
  uint32_t descriptor_deferred;
};

enum bk7258_mb_link_state
{
  BK7258_MB_LINK_DOWN = 0,
  BK7258_MB_LINK_ABORTING,
  BK7258_MB_LINK_PROBING,
  BK7258_MB_LINK_READY,
  BK7258_MB_LINK_QUIESCING
};

typedef int (*bk7258_mbox_callback_t)
  (const struct bk7258_mb_wire_message *message);
typedef int (*bk7258_mb_channel_rx_t)
  (const struct bk7258_mb_wire_message *message, uint8_t *ack_flags,
   void *arg);
typedef void (*bk7258_mb_tx_complete_t)
  (const struct bk7258_mb_wire_message *ack, int result, void *arg);
typedef void (*bk7258_mb_link_callback_t)
  (enum bk7258_mb_link_state state, void *arg);
typedef void (*bk7258_mb_uart_callback_t)(void *arg);

int bk7258_mbox_init(void);
int bk7258_mbox_send(uint8_t destination, const uint32_t data[2]);
bool bk7258_mbox_smp_ready(void);
#ifdef CONFIG_SMP
int bk7258_mbox_secondary_init(void);
void bk7258_smp_ipi_receive(int irq, void *context, uint32_t command);
#endif
uint32_t bk7258_mbox_rx_status(void);
void bk7258_mbox_set_callback(bk7258_mbox_callback_t callback);
void bk7258_mbox_get_stats(struct bk7258_mbox_stats *stats);
void bk7258_mbox_kick_rx(void);
void bk7258_mbox_discard_deferred(void);

int bk7258_mailbox_init(void);
int bk7258_mailbox_start(void);
int bk7258_mailbox_workers_start(void);
int bk7258_mailbox_workers_activate(void);
int bk7258_mailbox_send_wire(uint8_t logical_channel,
                             const struct bk7258_mb_wire_message *message,
                             bk7258_mb_tx_complete_t callback, void *arg);
int bk7258_mailbox_register_rx(uint8_t logical_channel,
                               bk7258_mb_channel_rx_t callback, void *arg);
int bk7258_mailbox_start_probe(void);
void bk7258_mailbox_probe_complete(bool ready);
void bk7258_mailbox_force_reset(void);
enum bk7258_mb_link_state bk7258_mailbox_link_state(void);
bool bk7258_mailbox_link_ready(void);
int bk7258_mailbox_wait_link_ready(unsigned int timeout_ms);
void bk7258_mailbox_set_link_callback(bk7258_mb_link_callback_t callback,
                                       void *arg);
uint32_t bk7258_mailbox_peer_reset_generation(void);

/* Compatibility APIs used by the existing HW_CTRL and PWC services. */

int bk7258_mbox_send_message(uint8_t command, uint8_t logical_channel,
                             uint32_t param1, uint32_t param2,
                             uint32_t param3);
int bk7258_mailbox_send_pwc(uint8_t command, uint32_t p1, uint32_t p2,
                            uint32_t p3);
void bk7258_mailbox_set_pwc_rx(int (*callback)(const void *message));
int bk7258_mailbox_wait_hw_control(unsigned int timeout_ms);
int bk7258_mailbox_wait_pwc(unsigned int timeout_ms);
void bk7258_mailbox_dump_stats(void);
int bk7258_ipc_heartbeat_start(void);
void bk7258_ipc_heartbeat_poll(void);

int bk7258_mb_uart_init(void);
int bk7258_mb_uart_worker_start(void);
int bk7258_mb_uart_worker_activate(void);
void bk7258_mb_uart_start(void);
void bk7258_mb_uart_request_state(void);
ssize_t bk7258_mbox_uart_write(const uint8_t *data, size_t length);
ssize_t bk7258_mbox_uart_read(uint8_t *data, size_t length,
                              unsigned int *status);
void bk7258_mbox_uart_early_init(void);
bool bk7258_mbox_uart_rxavailable(void);
bool bk7258_mbox_uart_txready(void);
bool bk7258_mbox_uart_txempty(void);
void bk7258_mbox_uart_rxflowcontrol(bool upper);
void bk7258_mbox_uart_set_callback(bk7258_mb_uart_callback_t callback,
                                   void *arg);
int bk7258_mbox_uart_flush(unsigned int timeout_ms);
void bk7258_mbox_uart_dump_stats(void);

#endif
