############################################################################
# Persistent configuration (kvdb) - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = kvdb
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_KVDB_TOOL)

MAINSRC = kvdb_tool_main.c

include $(APPDIR)/Application.mk
