############################################################################
# BK7258 UART Ctrl-C test - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = ctrlc_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_CTRLC_TEST)

MAINSRC = hello_app_main.c

include $(APPDIR)/Application.mk
