############################################################################
# BK7258 manual SD-NAND initialization - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = sdnand_init
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_264_SDNAND_INIT)

MAINSRC = sdnand_init_main.c

include $(APPDIR)/Application.mk
